### ISSUE TITLE
​​how to classify that what is level 1 and not ?

### ISSUE THREAD

**Issue by ascendantaditya** [GSSoC24/Open-source-Practice#238]
​​how to classify that what is level 1 and not ?

**Comment by MeghashyamRavuru** [comment]
The mentor or Project admin will mention it, if it is not there please comment on that issue and ask them to label it as level 1 or any.

**Comment by ascendantaditya** [comment]
sir i've contributed to an repo but the labels are not visible there , repo name : AutomaDesk
